### ISSUE TITLE
A skip attribute macro

### ISSUE THREAD

**Issue by matiu2** [sfackler/staged-builder#12]
This is the best and most un-derated builder crate. Thank you.

Use case:

```
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ListInstrumentsRequest<'a> {
    #[serde(skip)]
    accounts: &'a Accounts<'a>,
    /// List of instruments to query specifically.
    instruments: Vec<String>,
}
```

I have more than just stuff to build in the struct so when it comes time to build I can use it to make an REST request.

I want the builder to ignore accounts in the example above.

**Comment by sfackler** [comment]
How would the builder build a ListInstrumentsRequest without the accounts field?

**Comment by matiu2** [comment]
I imagined:

```rust
fn start_request() -> ListInstrumentsRequest<'a>::Builder {
  ListInstrumentsRequest{ accounts: self, ..Default().. }.builder()
}

async fn use() -> ... {
    start_request().instruments(..).build().send().await
}
```

**Comment by sfackler** [comment]
How is that any different from this?

```rust
fn start_request(&self) -> FinalStageBuilder {
    ListInstrumentsRequest::builder().accounts(self)
}
```

**Comment by matiu2** [comment]
Because the `accounts` field is a reference, it needs a value to construct the object.

I guess I could probably work around it with some smart pointers or something.

I  withdraw my request. Thank you for your time and all the best to you.
